TestSuite[{
	"Test/DefaultOptions.mt",
	"Test/ApplyToInput.mt",
	"Test/InputWrapper.mt",
	"Test/ApplyToInput$InputWrapper.mt",
	"Test/ApplyToExpected.mt",
	"Test/ExpectedWrapper.mt",
	"Test/ApplyToExpected$ExpectedWrapper.mt"
	,
	"TestN/Basic.mt",
	"TestN/Errors.mt",
	"TestN/Options.mt"
}]