TestSuite[{
	"TestEnvironment/BeginTestEnvironment.mt",
	"TestEnvironment/EndTestEnvironment.mt"
	,
	"Package/MakeString.mt",
	"Package/GetTestingFunctions.mt",
	"Package/TestQ.mt",
	"Package/ProtectTestSyntax.mt",
	"Package/AssignTestFeatures.mt",
	"Package/AddTestDefaultFunction.mt",
	"Package/ThrowTestError.mt",
	"Package/CatchTestError.mt",
	"Package/TestCaseEnvironment.mt"
	,
	"TestsOfTests/TestsOfTestsEnvironment.mt",
	"TestsOfTests/TestOfTests.mt"
	,
	"Tests/Test/DefaultOptions.mt",
	"Tests/Test/ApplyToInput.mt",
	"Tests/Test/InputWrapper.mt",
	"Tests/Test/ApplyToInput$InputWrapper.mt",
	"Tests/Test/ApplyToExpected.mt",
	"Tests/Test/ExpectedWrapper.mt",
	"Tests/Test/ApplyToExpected$ExpectedWrapper.mt",
	"Tests/TestN/Basic.mt",
	"Tests/TestN/Errors.mt",
	"Tests/TestN/Options.mt"
}]