TestSuite[{
	"MUnitVersionsCompatibility.mt"
	,
	"BeginEndTestEnvironment.mt"
	,
	"Package/TestQ.mt",
	"Package/ProtectTestSyntax.mt",
	"Package/AssignTestFeatures.mt",
	"Package/AddTestDefaultFunction.mt",
	"Package/ThrowCatchTestError.mt",
	"Package/TestCaseEnvironment.mt"
	,
	"TestsOfTests/TestOfTests.mt"
}]